export const categories = [
  {
    title: "ایران‌خودرو",
    slug: "ikco",
    description: "قطعات مناسب خودروهای ایران‌خودرو",
  },
  {
    title: "سایپا",
    slug: "saipa",
    description: "قطعات مناسب خودروهای سایپا",
  },
  {
    title: "قطعات ترمز",
    slug: "brake-parts",
    description: "دیسک ترمز، کاسه چرخ، سیلندر ترمز و بیشتر",
  },
  {
    title: "بلبرینگ",
    slug: "bearing",
    description: "انواع بلبرینگ چرخ جلو و عقب",
  },
];

export const products = [
  {
    id: 1,
    name: "دیسک ترمز جلو پژو 405، پارس و سمند",
    code: "6010101",
    price: "۱۳,۱۱۵,۰۰۰    ریال",
    stock: "موجود",
    image: "/images/6010101.jpg",
    slug: "front-brake-disc-peugeot-405-pars-samand",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["پژو 405", "پارس", "سمند"],
    shortDescription: "دیسک ترمز جلو مناسب پژو 405، پارس و سمند.",
    description:
      "این محصول برای خودروهای پژو 405، پارس و سمند طراحی شده و برای استفاده روزمره و عملکرد مطمئن در سیستم ترمز مناسب است.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 2,
    name: "کاسه چرخ عقب پژو 405",
    code: "6020101",
    price: "۱۵,۲۴۵,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6020101.jpg",
    slug: "rear-wheel-drum-peugeot-405",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["پژو 405"],
    shortDescription: "کاسه چرخ عقب مناسب پژو 405.",
    description:
      "کاسه چرخ عقب مناسب پژو 405 با عملکرد استاندارد و کیفیت مناسب برای بازار داخلی.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 3,
    name: "پولی سر میل لنگ پژو 405",
    code: "6050101",
    price: "۹,۸۰۰,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6050101.jpg",
    slug: "crankshaft-pulley-peugeot-405",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["پژو 405"],
    shortDescription: "پولی سر میل لنگ مناسب پژو 405.",
    description: "قطعه مناسب برای پژو 405 با کیفیت ساخت مناسب و کارکرد قابل اتکا.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 4,
    name: "دیسک ترمز جلو پژو 206 تیپ 5",
    code: "6010301",
    price: "۱۴,۶۹۷,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010301.jpg",
    slug: "front-brake-disc-peugeot-206-type-5",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["پژو 206 تیپ 5"],
    shortDescription: "دیسک ترمز جلو مناسب پژو 206 تیپ 5.",
    description:
      "این محصول برای پژو 206 تیپ 5 طراحی شده و در ترمزگیری عملکرد مناسب و پایدار ارائه می‌دهد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 5,
    name: "دیسک ترمز جلو پژو 206 تیپ 2 و 3",
    code: "6010302",
    price: "۱۱,۶۴۶,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010302.jpg",
    slug: "front-brake-disc-peugeot-206-type-2-3",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["پژو 206 تیپ 2", "پژو 206 تیپ 3"],
    shortDescription: "دیسک ترمز جلو مناسب پژو 206 تیپ 2 و 3.",
    description:
      "دیسک ترمز جلو مناسب پژو 206 تیپ 2 و 3 با کیفیت ساخت مناسب و عملکرد استاندارد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 6,
    name: "دیسک ترمز جلو سمند ماندو",
    code: "6010701",
    price: "۱۵,۵۰۰,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010701.jpg",
    slug: "front-brake-disc-samand-mando",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["سمند"],
    shortDescription: "دیسک ترمز جلو مناسب سمند ماندو.",
    description:
      "این دیسک ترمز برای خودروهای سمند ماندو مناسب است و برای کاربری روزمره طراحی شده است.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 7,
    name: "دیسک ترمز جلو دنا پلاس",
    code: "6011101",
    price: "۱۸,۸۹۷,۰۰۰     ریال",
    stock: "موجود",
    image:
      "https://images.unsplash.com/photo-1613214149922-f1809c99b414?auto=format&fit=crop&w=800&q=80",
    slug: "front-brake-disc-dena-plus",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["دنا پلاس"],
    shortDescription: "دیسک ترمز جلو مناسب دنا پلاس.",
    description:
      "دیسک ترمز جلو مناسب دنا پلاس با کیفیت مناسب و عملکرد ترمزگیری قابل اعتماد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 8,
    name: "دیسک ترمز جلو ال 90",
    code: "6010501",
    price: "۱۴,۱۱۷,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010501.jpg",
    slug: "front-brake-disc-l90",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["ال 90"],
    shortDescription: "دیسک ترمز جلو مناسب ال 90.",
    description: "محصول مناسب خودرو ال 90 با ساختار استاندارد و کیفیت مناسب.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 9,
    name: "دیسک ترمز جلو پیکان",
    code: "6010401",
    price: "۸,۷۹۳,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010401.jpg",
    slug: "front-brake-disc-paykan",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["پیکان"],
    shortDescription: "دیسک ترمز جلو مناسب پیکان.",
    description:
      "دیسک ترمز جلو مناسب خودرو پیکان با کیفیت مناسب برای استفاده روزمره.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 10,
    name: "دیسک جلو وانت پیکان (ای بی اس)",
    code: "6030202",
    price: "۱۰,۰۰۰,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6030202.jpg",
    slug: "front-disc-paykan-van-abs",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["وانت پیکان"],
    shortDescription: "دیسک جلو مناسب وانت پیکان ABS.",
    description: "محصول مناسب وانت پیکان با سیستم ABS و کیفیت ساخت مناسب.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 11,
    name: "کاسه چرخ عقب پیکان",
    code: "6020301",
    price: "۱۲,۲۳۲,۰۰۰     ریال",
    stock: "موجود",
    image:
      "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=800&q=80",
    slug: "rear-wheel-drum-paykan",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["پیکان"],
    shortDescription: "کاسه چرخ عقب مناسب پیکان.",
    description:
      "کاسه چرخ عقب مناسب پیکان با کیفیت استاندارد و عملکرد قابل اتکا.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 12,
    name: "دیسک ترمز جلو آر دی",
    code: "6010801",
    price: "۱۰,۰۰۰,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010801.jpg",
    slug: "front-brake-disc-rd",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["آر دی"],
    shortDescription: "دیسک ترمز جلو مناسب آر دی.",
    description:
      "دیسک ترمز جلو مناسب آر دی با کیفیت ساخت مناسب و عملکرد استاندارد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 13,
    name: "دیسک ترمز جلو روآ",
    code: "6010802",
    price: "۱۱,۰۰۰,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010802.jpg",
    slug: "front-brake-disc-roa",
    category: "brake-parts",
    brand: "ایران‌خودرو",
    compatibleCars: ["روآ"],
    shortDescription: "دیسک ترمز جلو مناسب روآ.",
    description: "محصول مناسب خودرو روآ با ساختار استاندارد و کیفیت مناسب.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },

  {
    id: 14,
    name: "دیسک ترمز جلو پراید",
    code: "6010201",
    price: "۸,۵۰۰,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010201.jpg",
    slug: "front-brake-disc-pride",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "دیسک ترمز جلو مناسب پراید.",
    description:
      "دیسک ترمز جلو مناسب خانواده پراید با کیفیت مناسب و عملکرد قابل اعتماد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 15,
    name: "کاسه چرخ عقب پراید (ای بی اس)",
    code: "6020201",
    price: "۱۰,۸۱۵,۰۰۰     ریال",
    stock: "موجود",
    image:
      "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=800&q=80",
    slug: "rear-wheel-drum-pride-abs",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "کاسه چرخ عقب ABS مناسب پراید.",
    description:
      "کاسه چرخ عقب مناسب پراید ABS با کیفیت استاندارد و عملکرد مناسب.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 16,
    name: "کاسه چرخ عقب قدیم پراید",
    code: "6020202",
    price: "۹,۳۱۵,۰۰۰     ریال",
    stock: "موجود",
    image:
      "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=800&q=80",
    slug: "rear-wheel-drum-old-pride",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "کاسه چرخ عقب قدیم مناسب پراید.",
    description:
      "کاسه چرخ عقب قدیم پراید با کیفیت مناسب و ساختار استاندارد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 17,
    name: "کاسه چرخ عقب جدید پراید",
    code: "6020203",
    price: "۹,۳۱۵,۰۰۰     ریال",
    stock: "موجود",
    image:
      "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=800&q=80",
    slug: "rear-wheel-drum-new-pride",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "کاسه چرخ عقب جدید مناسب پراید.",
    description:
      "کاسه چرخ عقب جدید پراید با کیفیت ساخت مناسب و کارکرد قابل اتکا.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 18,
    name: "کاسه چرخ عقب وانت پراید",
    code: "6020204",
    price: "۱۷,۰۱۸,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6020204.jpg",
    slug: "rear-wheel-drum-pride-van",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["وانت پراید"],
    shortDescription: "کاسه چرخ عقب مناسب وانت پراید.",
    description: "کاسه چرخ عقب مناسب وانت پراید با دوام و کیفیت مناسب.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 19,
    name: "سیلندر ترمز چرخ عقب پراید",
    code: "6030201",
    price: "۳,۹۰۰,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6030201.jpg",
    slug: "rear-brake-cylinder-pride",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "سیلندر ترمز چرخ عقب مناسب پراید.",
    description:
      "سیلندر ترمز عقب مناسب پراید با کیفیت ساخت مناسب و عملکرد استاندارد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 20,
    name: "دیسک ترمز تیبا، ساینا و کوییک",
    code: "6010601",
    price: "۱۲,۵۶۰,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010601.jpg",
    slug: "front-brake-disc-tiba-saina-quick",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["تیبا", "ساینا", "کوییک"],
    shortDescription: "دیسک ترمز مناسب تیبا، ساینا و کوییک.",
    description:
      "محصول مناسب تیبا، ساینا و کوییک با کیفیت مناسب و ترمزگیری استاندارد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 21,
    name: "کاسه چرخ تیبا",
    code: "6020601",
    price: "۱۳,۱۱۴,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6020601.jpg",
    slug: "rear-wheel-drum-tiba",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["تیبا"],
    shortDescription: "کاسه چرخ مناسب تیبا.",
    description:
      "کاسه چرخ تیبا با کیفیت استاندارد و عملکرد مناسب برای کاربری روزمره.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 22,
    name: "سیلندر ترمز چرخ عقب تیبا",
    code: "6030101",
    price: "۴,۵۰۰,۰۰۰     ریال",
    stock: "موجود",
    image:
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80",
    slug: "rear-brake-cylinder-tiba",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["تیبا"],
    shortDescription: "سیلندر ترمز چرخ عقب مناسب تیبا.",
    description:
      "محصول مناسب تیبا با کیفیت مناسب و کارکرد استاندارد در سیستم ترمز.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 23,
    name: "دیسک ترمز جلو نیسان",
    code: "6010901",
    price: "۱۷,۲۳۳,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010901.jpg",
    slug: "front-brake-disc-nissan",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["نیسان"],
    shortDescription: "دیسک ترمز جلو مناسب نیسان.",
    description:
      "دیسک ترمز مناسب نیسان با کیفیت مناسب و عملکرد ترمزگیری استاندارد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },
  {
    id: 24,
    name: "دیسک ترمز جلو وانت مزدا",
    code: "6010902",
    price: "۱۳,۲۳۷,۰۰۰     ریال",
    stock: "موجود",
    image: "/images/6010902.jpg",
    slug: "front-brake-disc-mazda-pickup",
    category: "brake-parts",
    brand: "سایپا",
    compatibleCars: ["وانت مزدا"],
    shortDescription: "دیسک ترمز جلو مناسب وانت مزدا.",
    description:
      "محصول مناسب وانت مزدا با کیفیت ساخت مناسب و ترمزگیری قابل اعتماد.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال مستقیم پس از ثبت سفارش",
  },

  {
    id: 25,
    name: "بلبرینگ چرخ جلو جدید پراید",
    code: "6040101",
    price: "تماس بگیرید",
    stock: "استعلام قیمت",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    slug: "front-wheel-bearing-new-pride",
    category: "bearing",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "بلبرینگ چرخ جلو جدید مناسب پراید.",
    description:
      "برای این محصول قیمت هنوز ثبت نشده است. برای استعلام قیمت با واحد فروش تماس بگیرید.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال پس از هماهنگی",
  },
  {
    id: 26,
    name: "بلبرینگ چرخ جلو قدیم پراید",
    code: "6040102",
    price: "تماس بگیرید",
    stock: "استعلام قیمت",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    slug: "front-wheel-bearing-old-pride",
    category: "bearing",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "بلبرینگ چرخ جلو قدیم مناسب پراید.",
    description:
      "برای این محصول قیمت هنوز ثبت نشده است. برای استعلام قیمت با واحد فروش تماس بگیرید.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال پس از هماهنگی",
  },
  {
    id: 27,
    name: "بلبرینگ چرخ عقب کوچک جدید پراید",
    code: "6040103",
    price: "تماس بگیرید",
    stock: "استعلام قیمت",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    slug: "rear-wheel-bearing-small-new-pride",
    category: "bearing",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "بلبرینگ چرخ عقب کوچک جدید مناسب پراید.",
    description:
      "برای این محصول قیمت هنوز ثبت نشده است. برای استعلام قیمت با واحد فروش تماس بگیرید.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال پس از هماهنگی",
  },
  {
    id: 28,
    name: "بلبرینگ چرخ عقب بزرگ پراید و چرخ جلو پیکان",
    code: "6040104",
    price: "تماس بگیرید",
    stock: "استعلام قیمت",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    slug: "rear-wheel-bearing-big-pride-front-paykan",
    category: "bearing",
    brand: "سایپا",
    compatibleCars: ["پراید", "پیکان"],
    shortDescription: "بلبرینگ چرخ عقب بزرگ پراید و چرخ جلو پیکان.",
    description:
      "برای این محصول قیمت هنوز ثبت نشده است. برای استعلام قیمت با واحد فروش تماس بگیرید.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال پس از هماهنگی",
  },
  {
    id: 29,
    name: "بلبرینگ چرخ عقب کوچک قدیم پراید",
    code: "6040105",
    price: "تماس بگیرید",
    stock: "استعلام قیمت",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    slug: "rear-wheel-bearing-small-old-pride",
    category: "bearing",
    brand: "سایپا",
    compatibleCars: ["پراید"],
    shortDescription: "بلبرینگ چرخ عقب کوچک قدیم مناسب پراید.",
    description:
      "برای این محصول قیمت هنوز ثبت نشده است. برای استعلام قیمت با واحد فروش تماس بگیرید.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال پس از هماهنگی",
  },
  {
    id: 30,
    name: "بلبرینگ چرخ عقب پژو 405 و چرخ جلو 206 تیپ 5",
    code: "6040106",
    price: "تماس بگیرید",
    stock: "استعلام قیمت",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    slug: "rear-bearing-peugeot-405-front-206-type-5",
    category: "bearing",
    brand: "ایران‌خودرو",
    compatibleCars: ["پژو 405", "پژو 206 تیپ 5"],
    shortDescription: "بلبرینگ چرخ عقب پژو 405 و چرخ جلو 206 تیپ 5.",
    description:
      "برای این محصول قیمت هنوز ثبت نشده است. برای استعلام قیمت با واحد فروش تماس بگیرید.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال پس از هماهنگی",
  },
  {
    id: 31,
    name: "بلبرینگ چرخ جلو 206 تیپ 2",
    code: "6040301",
    price: "تماس بگیرید",
    stock: "استعلام قیمت",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    slug: "front-wheel-bearing-206-type-2",
    category: "bearing",
    brand: "ایران‌خودرو",
    compatibleCars: ["پژو 206 تیپ 2"],
    shortDescription: "بلبرینگ چرخ جلو مناسب پژو 206 تیپ 2.",
    description:
      "برای این محصول قیمت هنوز ثبت نشده است. برای استعلام قیمت با واحد فروش تماس بگیرید.",
    warranty: "دارای ضمانت اصالت و سلامت فیزیکی کالا",
    shipping: "ارسال پس از هماهنگی",
  },
];

export const offers = [
  {
    title: "پیشنهاد ویژه هفته",
    subtitle: "برخی محصولات با شرایط ویژه عرضه می‌شوند",
  },
  {
    title: "خرید عمده",
    subtitle: "برای سفارش‌های عمده با واحد فروش تماس بگیرید",
  },
];